#! /usr/bin/python
#
# ospjob
#
# usage: ospjob jobcode [sequence] [shot]
#
# 

# From Python
import imp
import os
import sys
# From ospenv
import osp

if __name__ == '__main__':

    # List all set job envars if ospjob was called without parameters.
    if len(sys.argv) <= 1:
        print osp.job_env()
        sys.exit(0)
    
    # Set the job.
    for job in osp.jobs():
        config = imp.load_source('job_config', osp.job_config_file(job))
        if config.jobcode == sys.argv[1]:
            print "export OSP_JOB_PATH=" + job
            print "export OSP_JOB_CODE=" + config.jobcode
            print "export OSP_JOB_NAME=" + config.jobname
    
    # Set the sequence if any.
    if sys.argv[2] is not None:
        print "export OSP_SEQ_NAME=" + sys.argv[2]
    
    # Set the shot if any.
    if sys.argv[3] is not None:
        print "export OSP_SHOT_NAME=" + sys.argv[3]
